# Generated by Django 4.1.1 on 2023-03-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=600)),
                ('phone_number', models.IntegerField()),
                ('email_id', models.EmailField(max_length=100)),
                ('nationality', models.CharField(max_length=200)),
            ],
        ),
    ]
